[theme]
primaryColor = "#E91E63"
backgroundColor = "#FFF0F5"
secondaryBackgroundColor = "#E3F2FD"  # <--- To pole często steruje tłem list rozwijanych i widgetów w Streamlicie!
textColor = "#4A0E2E"
font = "sans serif"
